### ISSUE TITLE
Remove Hue & Brightness Slider.

### ISSUE THREAD

**Issue by jamesike** [johankasperi/SwiftHSVColorPicker#11]
As the title says...

**Comment by schystz** [comment]
Hi @J4awesome, did you found your way to remove the slider or selected color view? I am unable to access these properties from `SwiftHSVColorPicker` class. I tried creating an instance of `ColorWheel` but Xcode is complaining that it is an unknown type. I think this is because of the default `internal` access control for classes in Swift 3.
