### ISSUE TITLE
Color Picker much larger than view controller width

### ISSUE THREAD

**Issue by hipwelljo** [johankasperi/SwiftHSVColorPicker#4]
I embeded a SwiftHSVColorPicker UIView in a view controller storyboard, used auto layout to align its leading and trailing to the superview, but when the view controller is shown the color picker is much larger than the width of the view controller. It's making it 600x600 - the size of the scene in the storyboard. Here you can see the issue from the view debugger.
![screen shot 2016-03-03 at 4 19 10 pm](https://cloud.githubusercontent.com/assets/6282848/13513067/bcc9a834-e15b-11e5-9b70-a1c969822489.png)

**Comment by gunawanlie** [comment]
I assumed you trigger the setup subviews for this picker via .setViewColor before the auto layout constraint totally refreshed (ex: like in viewDidLoad or viewWillAppear), and in your case, since you do not setup the layout constraint with fixed width like in the example, the width that used when setting up this picker is not the one that fit the actual screen (which is supposed to be screen width - leading constraint - trailing constraint).

You can avoid this by calling the .setViewColor after the the layout constraint followed the actual screen size, like in viewDidAppear

**Comment by johankasperi** [comment]
Just as previous comments says this depends on when you initialize the colorpicker. However this has been fixed in the latest version. So please try the latest version and let me know if the issue still exists.
